### PR TITLE
Add VS17 informations

### PR DESCRIPTION
**Pull request by macintoshplus**

### CODE REVIEW

**Comment by cmb69** [comment]
Thank you!

See also #7, which uses a more conservative SDK; not sure what to prefer.

**Comment by macintoshplus** [comment]
The choice is not easy. I prefer the older SDK to keep more compatible with old VisualStudio installation.

I have to test the library build with an older version without installing it.

I don't think that using one version or another changes much in the generated binary. The libraries do not use the new features of the latest SDKs.

**Comment by cmb69** [comment]
I remember that a while ago I had issues (don't remember exactly what it was) with some of the newer SDKs (might have been 10.26100.0, but I'm not sure), and had to uninstall it to go on. 10.0.20348.0 is well tested I think, but 10.0.22621.0 is probably okay, too.

**Comment by macintoshplus** [comment]
I just tested, it is not possible to build without the SDK installed.

I had a problem with the SDK (the latest one) during my compilation tests on ARM64. I had to modify a header file of the SDK. I hope I will not have to do this modification again with an older version.

What is the minimum Windows version for PHP 8.4?

**Comment by cmb69** [comment]
> I had to modify a header file of the SDK.

That sounds adventurous.

> What is the minimum Windows version for PHP 8.4?

Same as for PHP 8.3: Windows 8/Server 2012 (https://www.php.net/manual/en/install.windows.requirements.php).

**Comment by macintoshplus** [comment]
> > I had to modify a header file of the SDK.
> 
> That sounds adventurous.

Yes, but I can accept for experimental build. Not for production build.


> > What is the minimum Windows version for PHP 8.4?
> 
> Same as for PHP 8.3: Windows 8/Server 2012 (https://www.php.net/manual/en/install.windows.requirements.php).

Thank you. The SDK version is the same one used for PHP 8.3. It's sound good.

**Comment by cmb69** [comment]
PR #7 has been merged, so there are now merge conflicts. From what I can tell, only the Windows SDK update for vs17 would still be relevant, and I'm fine going with 10.0.22621.0 (I'm using this for quite a while, and haven't noticed any issues).

Could you please rebase onto current master?

**Comment by macintoshplus** [comment]
I have rebase this branch onto master.

**Comment by cmb69** [comment]
Thank you!

**Pull request merged**
